# Book settings
title: Deep Learning Portfolio
author: Your Name  # Update with your actual name
logo: logo.png
copyright: "2025"

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: off  # Set to 'auto' if you want to re-run notebooks on build
  timeout: 100
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/hyunkael/Deep-Learning-Portfolio
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  baseurl: https://hyunkael.github.io/Deep-Learning-Portfolio/
  extra_footer: |
    <div>
      <p>Built with <a href="https://jupyterbook.org">Jupyter Book</a></p>
    </div>

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# Sphinx configuration
sphinx:
  extra_extensions:
    - sphinx_design
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      navigation_with_keys: false
      show_toc_level: 2
      repository_url: https://github.com/hyunkael/Deep-Learning-Portfolio
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      logo_only: false
      show_navbar_depth: 2
    html_css_files:
      - custom.css
